name: Dependency Update

on:
    schedule:
        - cron: "0 0 * * 0" # Weekly updates (Sunday at midnight)
    workflow_dispatch:

jobs:
    dependency-update:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Setup Java
              uses: actions/setup-java@v3
              with:
                  java-version: 23
                  distribution: temurin

            - name: Update Dependencies
              run: |
                  mvn versions:display-dependency-updates
                  mvn versions:update-properties
                  mvn versions:commit

            - name: Commit and Push Updates
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"
                  git add .
                  git commit -m "Update Maven Dependencies" || echo "No changes to commit"
                  git push
